GET http://localhost:8080/api/v1/getMovieName/{{name}}
###

GET http://localhost:8080/api/v1/getMovieId/{{id}}
Content-Type: application/json
###

PUT http://localhost:8080/api/v1/updateMovie/{{idToUpdate}}
Content-Type: application/json

{
  "name": "1 Night in China"
}

###

PUT http://localhost:8080/api/v1/createMovie
Content-Type: application/json

###

DELETE http://localhost:8080/api/v1/deleteMovie/{{idToDelete}}
Content-Type: application/json